# These are supported funding model platforms

github: [Toasterson] # Add your GitHub username here for GitHub Sponsors
patreon: # Add your Patreon username here if you have one
open_collective: # Add your Open Collective username here if you have one
ko_fi: # Add your Ko-fi username here if you have one
tidelift: # Add tidelift package info if you publish to package managers
community_bridge: # Add Community Bridge project name if applicable
liberapay: # Add your Liberapay username here if you have one
issuehunt: # Add your IssueHunt username here if you have one
otechie: # Add your Otechie username here if you have one
lfx_crowdfunding: # Add LFX Crowdfunding project name if applicable
custom: # Add up to 4 custom sponsorship URLs here, e.g., ['https://buymeacoffee.com/username']