apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: oxifed
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/youruser/oxifed # Replace with your repo
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oxifed-dev
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: oxifed
  targetNamespace: oxifed-dev
